apiVersion: v1
kind: Service
metadata:
  name: nodejs-hazelcast-client-svc
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: nodejs-hazelcast-client
  ports:
    - protocol: TCP
      targetPort: 8080 # donde escucha el pod
      port: 8080 # donde escucha e service
      nodePort: 30083
  type: NodePort