apiVersion: v1
kind: Service
metadata:
  name: nodejs-api2-svc
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: nodejs-api-2
  ports:
    - protocol: TCP
      name: tcp-nodejs-api2-svc
      targetPort: 8082 # donde escucha el pod
      port: 8082 # donde escucha e service
      nodePort: 30080
  type: NodePort