COMPUTED VALUES:
affinity: {}
clusterRoleCreator: true
cr:
  create: true
  name: kiali
  namespace: istio-system
  spec:
    deployment:
      accessible_namespaces:
      - '**'
debug:
  enabled: true
  verbosity: "1"
fullnameOverride: ""
image:
  pullPolicy: Always
  pullSecrets: []
  repo: quay.io/kiali/kiali-operator
  tag: v1.22.1
metrics:
  enabled: true
nameOverride: ""
nodeSelector: {}
onlyViewOnlyMode: false
podAnnotations: {}
priorityClassName: ""
replicaCount: 1
resources: {}
tolerations: []
watchNamespace: ""
