apiVersion: v1
kind: Service
metadata:
  name: nodejs-api1-svc
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: nodejs-api-1
  ports:
    - protocol: TCP
      targetPort: 8081 # donde escucha el pod
      port: 8081 # donde escucha e service
      nodePort: 30082
  type: NodePort