kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master-headless
  labels:
    app: "elasticsearch-stateful-set"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: "elasticsearch-stateful-set"
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300