kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-svc
spec:
  type: ClusterIP
  selector:
    app: "elasticsearch-stateful-set"
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300