apiVersion: v1
kind: Secret
metadata:
  name: secret-oci-streaming
type: Opaque
data:
  SASL_JAAS_CONFIG: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkucGxhaW4uUGxhaW5Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT1cInRkZWNsb3VkL2FwcF9taWNyb3NlcnZpY2lvc19wb2Mvb2NpZDEuc3RyZWFtcG9vbC5vYzEuaWFkLmFtYWFhYWFhNHUzdW13cWFrdTNqZnFheG1rM3ZibGN1Z2djY2Z6c3l1dmFwN294Y3V1YmlkdDdjZXBvcVwiIHBhc3N3b3JkPVwiR2JaZkYxLVBjLlYtY3NlTUdHNWlcIjs=