apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cb-for-the-entire-default-namespace
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
#    connectionPool:
#      tcp:
#        maxConnections: 1
#      http:
#        http1MaxPendingRequests: 1
#        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 5s
#      baseEjectionTime: 3m
      maxEjectionPercent: 100