apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-client-configuration
data:
  hazelcast-client.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.11.xsd"
    xmlns="http://www.hazelcast.com/schema/client-config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <network>
            <cluster-members>
                <address>my-release-hazelcast.default.svc.cluster.local</address>
            </cluster-members>
            <!-- <outbound-ports>
                <ports>34600</ports>
                <ports>34700-34710</ports>
            </outbound-ports> -->
            <smart-routing>false</smart-routing>
            <redo-operation>true</redo-operation>
            <connection-timeout>5000</connection-timeout>
            
        </network>
    </hazelcast-client>