apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast
    role: hazelcast
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5701
      targetPort: 5701
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30010