apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-hazelcast-1
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: my-release-hazelcast-1
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5701
      targetPort: 5701
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008